//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Claim
    {
        public int Claim_Id { get; set; }
        public Nullable<int> Bill_Id { get; set; }
        [Display(Name = "Claim Date")]
        public string Claim_Date { get; set; }
        [Display(Name = "Accident Place")]
        public string Accident_Place { get; set; }
        [Display(Name = "Accident Description")]
        public string Accident_Description { get; set; }
        [Display(Name = "Claim Amount")]
        public int Claim_Amount { get; set; }

        public virtual Billing Billing { get; set; }
    }
}
