//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Company_Admin
    {
        public int Admin_Id { get; set; }
        [Display(Name = "Admin Name")]
        public string Admin_Name { get; set; }
        [Display(Name = "Admin Password")]
        [DataType(DataType.Password)]
        public string Admin_Pass { get; set; }
        [Display(Name = "Admin Email")]
        public string Admin_Email { get; set; }
        [Display(Name = "Admin Phone")]
        public int Admin_Phone { get; set; }
    }
}
