//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.testimonials = new HashSet<testimonial>();
            this.Vehicles = new HashSet<Vehicle>();
        }

        public int Cust_Id { get; set; }
        [Display(Name = "CustomerName")]
        public string Cust_Name { get; set; }
        [Display(Name = "Address")]
        public string Cust_Add { get; set; }
        [Display(Name = "Phone number")]
        public string Cust_Phone { get; set; }
        [Display(Name = "Email")]
        public string Cust_Email { get; set; }
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Cust_Pass { get; set; }
        [Display(Name = "CNIC")]
        public int Cust_CNIC { get; set; }
        [Display(Name = "Username")]
        public string UserName { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<testimonial> testimonials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
