//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class InsurancePolicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsurancePolicy()
        {
            this.Purchases = new HashSet<Purchase>();
        }

        public int Pol_Id { get; set; }
        [Display(Name = "Policy Name")]
        public string PolicyName { get; set; }
        [Display(Name = "Estimated Amount")]
        public int Est_Amount { get; set; }
        [Display(Name = "Insurance Amount")]
        public int Ins_Amount { get; set; }
        [Display(Name = "Policy Duration")]
        public string Pol_Duration { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}
