//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Vehicle_Insurance_ManagmentEntities : DbContext
    {
        public Vehicle_Insurance_ManagmentEntities()
            : base("name=Vehicle_Insurance_ManagmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Billing> Billings { get; set; }
        public virtual DbSet<Claim> Claims { get; set; }
        public virtual DbSet<Company_Admin> Company_Admin { get; set; }
        public virtual DbSet<Company_Expense> Company_Expense { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<InsurancePolicy> InsurancePolicies { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<testimonial> testimonials { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
    }
}
