//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.Billings = new HashSet<Billing>();
        }

        public int Pur_Id { get; set; }
        [Display(Name = "Vehicle")]
        public Nullable<int> Vehicle { get; set; }
        [Display(Name = "Policy")]
        public Nullable<int> Pur_Pol { get; set; }
        [Display(Name = "Purchase Date")]
        
        public string Pur_Date { get; set; }
        [Display(Name = "Total Amount")]
        public int Total_Amt { get; set; }
        [Display(Name = "Policy Status")]
        public string PP_Status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billing> Billings { get; set; }
        public virtual InsurancePolicy InsurancePolicy { get; set; }
        public virtual Vehicle Vehicle1 { get; set; }
    }
}
