//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class testimonial
    {
        public int Test_ID { get; set; }
        [Display(Name = "Customer Testimonial")]
        public string Cust_Test { get; set; }
        [Display(Name = "Customer Name")]
        public Nullable<int> Cust_Name { get; set; }

        public virtual Customer Customer { get; set; }
    }
}
