//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Purchases = new HashSet<Purchase>();
        }

        public int Veh_Id { get; set; }
        [Display(Name = "Vehicle Name")]
        public string Veh_Name { get; set; }
        [Display(Name = "OwnerName")]
        public Nullable<int> Veh_OwnerName { get; set; }
        [Display(Name = "Vehicle Model")]
        public string Veh_Model { get; set; }
        [Display(Name = "Vehicle Version")]
        public string Veh_Version { get; set; }
        [Display(Name = "Vehicle Rate")]
        public int Veh_Rate { get; set; }
        [Display(Name = "Body Number")]
        public string Veh_BodyNo { get; set; }
        [Display(Name = "Enigne Number")]
        public string Veh_EngineNo { get; set; }
        [Display(Name = "Vehicle Number")]
        public Nullable<int> Veh_No { get; set; }

        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}
